FROM node:lts-hydrogen

WORKDIR /apps

COPY . .

RUN npm install --production

ENV NODE_ENV=production
ENV PORT=4002
ENV DATABASE_URL=postgresql://postgres:8g1ZvGuv2BVvqvze@db.hsrckjejcjmcgmoyswvg.supabase.co:5432/postgres


EXPOSE 4002

CMD ["node", "app.js"]